service: blog-api # Nome do serviço

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x # Use a versão de Node.js compatível
  stage: dev
  region: us-east-1 # Altere para a região desejada
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: posts
          method: any
      - http:
          path: posts/{id}
          method: any
      - http:
          path: posts/{id}/publish
          method: put

plugins:
  - serverless-offline
